version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y terraform

  pre_build:
    commands:
    
pre_build:
  commands:
    - echo "==== Terraform Init Debug Start ===="
    - pwd
    - ls -la
    - echo "---- backend.tf ----"
    - cat backend.tf
    - echo "---- provider.tf ----"
    - cat provider.tf
    - echo "---- Terraform Init ----"
    - terraform init -input=false -no-color -reconfigure

  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
