version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y terraform

  pre_build:
    commands:
      - echo "Terraform version"
      - terraform version
      - echo "Initializing Terraform"
      - terraform init -input=false

  build:
    commands:
      - echo "Running Terraform plan"
      - terraform plan
      - echo "Applying Terraform"
      - terraform apply -auto-approve

